# Generated by Django 5.1.6 on 2025-02-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField(default=1)),
                ('hp', models.IntegerField(default=100)),
                ('atk', models.IntegerField(default=10)),
                ('defe', models.IntegerField(default=5)),
                ('spd', models.IntegerField(default=10)),
                ('stm', models.IntegerField(default=50)),
                ('mtx', models.IntegerField(default=5)),
            ],
        ),
    ]
