# Generated by Django 5.1.6 on 2025-02-14 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='defe',
            new_name='defense',
        ),
    ]
